theme: jekyll-theme-minimal
title: Defra AI Agents Playbook
description: This playbook is a living document that provides practical guidance on evaluating, designing, and deploying AI Agents, AI Workflows, and Multi-Agent Systems within Defra. It is tailored to Defra’s unique operational context and challenges, and aligns with UK Government standards for responsible and effective use of AI.
baseurl: '/defra-ai-agents'
logo: /assets/images/defra-logo.svg
version: 2.0.3
css_version: 2.0.3

# Build settings
source: .
sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass
    - node_modules

# Additional settings
markdown: kramdown
show_downloads: false
google_analytics: # Add your Google Analytics tracking ID here if needed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Include files that are normally excluded
include:
  - CONTRIBUTING.md

# Exclude files from processing
exclude:
  - .obsidian/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/